insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0409-1626', 'Maypother', 'Liam', '19 Forest Run Crossing', 'DABS', 'Jhumra');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('51079-941', 'Strutton', 'Claudine', '0 Melody Alley', 'SAVN', 'Bomomani');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0268-1402', 'Broz', 'Duncan', '83 John Wall Place', 'WBGK', 'Korosten’');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0338-1113', 'Proudman', 'Barri', '8 Starling Drive', 'SLSM', 'Évry');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('50436-0158', 'Hincham', 'Joete', '30 Donald Terrace', 'KJMS', 'Lüfeng');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('48951-8247', 'Cleeton', 'Derek', '13 Melvin Court', 'KWP', 'San Diego');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('60289-282', 'Gaywood', 'Philippa', '7745 Florence Parkway', 'KLZU', 'Lianzhou');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('12027-104', 'Greenalf', 'Vance', '93 Surrey Junction', 'OEDM', 'Angers');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('46122-274', 'Marran', 'Ronni', '3 Dapin Avenue', 'AYEB', 'Parigi');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('41190-951', 'Dufore', 'Evangeline', '1 Canary Hill', 'KSTC', 'Lérida');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0832-0300', 'Rawlingson', 'Werner', '4679 Schurz Hill', 'LPSJ', 'Narva');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('49288-0621', 'Elstub', 'Brandais', '7511 Northview Crossing', 'KUCA', 'Tomingad');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0944-8402', 'Fain', 'Zahara', '829 Oxford Crossing', 'CYXL', 'Sławatycze');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('13107-006', 'Cadding', 'Mackenzie', '86835 Sheridan Court', 'DAUT', 'Novyye Cherëmushki');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('55154-3875', 'Cubbino', 'Lura', '73407 Meadow Vale Plaza', 'LFBO', 'Makin Village');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('31357-040', 'Garnett', 'Ethelda', '20 Arizona Hill', 'NSAS', 'Kungsbacka');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('37808-056', 'Baterip', 'Munmro', '48339 Manufacturers Plaza', null, 'Washington');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('52125-926', 'Warby', 'Shayne', '71484 Spaight Plaza', 'KSDY', 'Tacheng');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('37000-617', 'Darwen', 'Sari', '580 Hansons Alley', 'EGXW', 'Tashla');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('57237-013', 'Coger', 'Guillema', '9780 Fairfield Parkway', 'A63', 'Tangping');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('68788-9994', 'Hasely', 'Griffy', '9754 Center Drive', 'FMSK', 'Aţ Ţawāḩīn');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0536-4122', 'Heavyside', 'Lyssa', '8 Bunker Hill Court', 'UUWR', 'Kebonkai');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('58232-6036', 'Van Cassel', 'Cristal', '7 Iowa Road', 'FBSK', 'Canis');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('54569-2376', 'Tenwick', 'Nance', '53 Fremont Court', 'TFFC', 'Lescar');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0078-0500', 'Gawkes', 'Rorie', '6 Dakota Alley', 'KNJK', 'Waihibar');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('49364-110', 'Kisby', 'Jonathan', '39634 West Crossing', 'GAGM', 'Sandaohezi');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('59572-205', 'Hayth', 'Rudd', '95 Caliangt Terrace', '4R7', 'Cambuí');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('49288-0905', 'Perring', 'Alexina', '89 Swallow Park', 'CKX', 'Kamenka');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('29336-322', 'Harvard', 'Corry', '5 Farragut Street', 'ESNH', 'Yushan');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('41163-423', 'Damato', 'Baily', '8858 Hollow Ridge Park', 'EFHK', 'Boychinovtsi');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0406-9907', 'Screach', 'Zandra', '51761 Elgar Center', 'ZMBR', 'Tsagaan-Ovoo');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0641-0493', 'Wickardt', 'Michel', '109 Walton Pass', 'CYXL', 'La Calera');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('54429-0103', 'Keenleyside', 'Mireielle', '71 Superior Parkway', 'KBBD', 'Saint-Avertin');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('98132-885', 'Notman', 'Laird', '24 Red Cloud Place', 'HSDN', 'Kiev');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('0641-6118', 'Ingley', 'Reinhard', '7 Northport Hill', 'KPHK', 'Krasnoshchekovo');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('35356-250', 'Grewar', 'Lilli', '587 Daystar Court', 'HKWJ', 'Chernomorets');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('58118-0107', 'Hardwich', 'Yanaton', '99130 Mallard Plaza', 'CYQY', 'Sagay');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('61957-0119', 'Masserel', 'Alejandrina', '0 Melvin Trail', 'SLRY', 'Agbor');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('36987-2864', 'Billsberry', 'Fletcher', '661 5th Drive', 'VRMM', 'Sijunjung');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('57664-146', 'Blayd', 'Zarah', '6695 Browning Circle', 'NZNS', 'Tiechang');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('49288-0747', 'Nand', 'Graeme', '9 Elka Lane', 'HAFN', 'Beijiang');
insert into client (CODE_CLIENT, NOM, PRENOM, ADRESSE, CODE_POSTAL, VILLE) values ('51824-018', 'Willgoose', 'Newton', '6 Anderson Road', 'FMNS', 'Al Mazzūnah');
